### ISSUE TITLE
Unable to detect @import filename of underscore prefix on Sass/Scss

### ISSUE THREAD

**Issue by okamoai** [mrmlnc/emitty#10]
Import file detection is not working under the following conditions.

- app.scss
- _foo.scss

```scss
/* app.scss */
@import "foo";
```

```js
console.log(emitty.storage())
/*
{
  'src/sass/app.scss': {
    dependencies: ['src/sass/foo.scss'],
    ctime: 1497971214488
  },
  'src/sass/_foo.scss': {
    dependencies: [],
    ctime: 1497962273042
   }
}
*/
```
It seems that the file path does not match the dependency path.

**Comment by mrmlnc** [comment]
I'll publish `emitty@1.4.0` today. Now `sass` and `scss` languages have `partials` option.

**Comment by mrmlnc** [comment]
Available in https://github.com/mrmlnc/emitty/releases/tag/1.4.0.
