### ISSUE TITLE
Pug не компилируется

### ISSUE THREAD

**Issue by a-gunderin** [mrmlnc/emitty#11]
При запуске gulp watch и сохранении любого pug файла консоль сообщает об успешном завершении таска 'templates', но в папку build ничего не падает, pug не компилируется. Если убрать 'global.watch = true;', то компилируется абсолютно всё, инкрементальный подход не работает. В чём может быть проблема? Делал всё по примеру =)))
Тестовый репозиторий: https://github.com/a-gunderin/incremental-html-template

**Comment by mrmlnc** [comment]
Привет, @a-gunderin,

Я склонировал твой репозиторий и запустил `gulp watch`, добавив `"start": "gulp watch"` в `scripts` – файлы компилируются по одному, как и должно быть.

**Comment by a-gunderin** [comment]
Добавил в package.json "start": "gulp watch" в scripts.
Не компилирует =(

**Comment by mrmlnc** [comment]
Хорошо, как ты вообще запускаешь gulp? У меня все работает, поэтому, чтобы тебе помочь, мне нужно знать:

 * как ты запускаешь gulp
 * node js version
 * npm version
 * emitty version

**Comment by a-gunderin** [comment]
- gulp watch с консоли
- v6.1.0
- 3.10.8
- 1.4.0
OS Windows 7

**Comment by alte0** [comment]
Привет! @mrmlnc у меня похоже то же самое. Поставил себе тестовый репозиторий автора, реакции ноль, даже папку не создает. Потом заменил gulp 4 на gulp 3.9.1 и заменил строчку  _gulp.watch('app/templates/**/*.pug', gulp.series('templates'))_ на _gulp.watch('app/templates/**/*.pug', ['templates'])_, компилировать стал, но не инкрементально.

- npm start
- v6.11.0
- v3.10.10
- v1.4.0
- OS Windows 10 (сборка последняя)

**Comment by mrmlnc** [comment]
Вы новые пользователи или раньше пользовались emitty? Вчера вышла новая версия пакета и, возможно, что-то сломалось.

Попробуй вывести `emitty.storage()` в консоль перед строкой https://github.com/a-gunderin/incremental-html-template/blob/master/gulpfile.js#L20 и добавьте вывод сюда.

Также попробуй добавить в `package.json` в секцию `scripts` следующую строку `"watch": "gulp watch"` и запустить её: `npm run watch`. Если работает, то проблема с путями у меня в модуле.

**Comment by alte0** [comment]
@mrmlnc Я в выходные начал сборку настраивать, версия была предыдущая (1.3.1)
**gulp 4** - 2 раза нажал сохранить, папки build нету.
```
[11:26:41] Starting 'watch'...
[11:26:48] Starting 'templates'...
{}
[11:26:48] Finished 'templates' after 129 ms
[11:27:33] Starting 'templates'...
{ 'app/templates/contacts.pug': { dependencies: [], ctime: 1498446400128 },
  'app/templates/privacy-policy.pug': { dependencies: [], ctime: 1498446400129 },
  'app/templates/services.pug': { dependencies: [], ctime: 1498446400130 },
  'app/templates/terms-of-use.pug': { dependencies: [], ctime: 1498447019845 },
  'app/templates/index.pug': { dependencies: [], ctime: 1498458408639 } }
[11:27:33] Finished 'templates' after 35 ms
```
**gulp 3.9.1** - 2 раза нажал сохранить. С первого раза папка появилась, html файлы есть, 2 сохранение всё перекомпилировалось.
```
[11:31:39] Starting 'watch'...
[11:31:39] Finished 'watch' after 23 ms
[11:32:11] Starting 'templates'...
{}
[11:32:11] Finished 'templates' after 433 ms
[11:33:57] Starting 'templates'...
{ 'app/templates/contacts.pug': { dependencies: [], ctime: 1498446400128 },
  'app/templates/privacy-policy.pug': { dependencies: [], ctime: 1498446400129 },
  'app/templates/services.pug': { dependencies: [], ctime: 1498446400130 },
  'app/templates/terms-of-use.pug': { dependencies: [], ctime: 1498447019845 },
  'app/templates/index.pug': { dependencies: [], ctime: 1498458731221 } }
[11:33:57] Finished 'templates' after 187 ms
```

**Comment by mrmlnc** [comment]
Звучит очень странно. А можно вывод вод этих команд:

```shell
$ gulp -v 
```

из директории с репозиторием:

```shell
$ ./node_modules/.bin/gulp -v
```

**Comment by alte0** [comment]
@mrmlnc  
```
$ gulp -v
[12:26:07] CLI version 3.9.1
[12:26:07] Local version 4.0.0-alpha.2
```
```
$ ./node_modules/.bin/gulp -v
[12:26:15] CLI version 1.3.0
[12:26:15] Local version 4.0.0-alpha.2
```

**Comment by mrmlnc** [comment]
Это, конечно, оптимистично, но попробуй удалить `node_modules` в директории репозитория и глобально установленный Gulp. Затем установить Gulp глобально, явно указав 4-ую версию и установив зависимости для директории репозитория. Кажется, что версии CLI должны быть другими — пришли версии, если они изменились.

Я давно не работал с Gulp, поэтому нужно копать глубже с моей стороны.

**Comment by alte0** [comment]
1) Решил попробовать из подсистемы linux, на 4 gulp компилирует тот файл, который сохраняешь.
На gulp 3.9.1 тупо всё перекомпилирует.
2) Установил gulpjs/gulp#4.0 глобально в windows. 
```
$ npm i gulpjs/gulp#4.0 -g
C:\Users\alte0\AppData\Roaming\npm\gulp -> C:\Users\alte0\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
C:\Users\alte0\AppData\Roaming\npm
`-- gulp@4.0.0-alpha.2  (git://github.com/gulpjs/gulp.git#38246c3f8b6dbb8d4ef657183e92d90c8299e22f)

$ gulp -v
[13:53:25] CLI version 1.3.0
[13:53:25] Local version 4.0.0-alpha.2

$ ./node_modules/.bin/gulp -v
[13:53:31] CLI version 1.3.0
[13:53:31] Local version 4.0.0-alpha.2
```
Не работает.

**Comment by a-gunderin** [comment]
> Вы новые пользователи или раньше пользовались emitty? Вчера вышла новая версия пакета и, возможно, что-то сломалось.

Я раньше не пользовался emitty.

>Попробуй вывести emitty.storage() в консоль перед строкой https://github.com/a-gunderin/incremental-html-template/blob/master/gulpfile.js#L20 и добавьте вывод сюда.
```
C:\Users\Andrei\Desktop\incremental-html-template>npm run watch
> starthtmltemplate@1.0.0 watch C:\Users\Andrei\Desktop\incremental-html-templat
e
> gulp watch
[23:26:22] Using gulpfile ~\Desktop\incremental-html-template\gulpfile.js
[23:26:22] Starting 'watch'...
[23:26:31] Starting 'templates'...
{}
[23:26:32] Finished 'templates' after 92 ms
[23:26:37] Starting 'templates'...
{ 'app/templates/index.pug': { dependencies: [], ctime: 1498508791703 },
  'app/templates/services.pug': { dependencies: [], ctime: 1498397303709 },
  'app/templates/terms-of-use.pug': { dependencies: [], ctime: 1498394000633 },
  'app/templates/contacts.pug': { dependencies: [], ctime: 1498394000618 },
  'app/templates/privacy-policy.pug': { dependencies: [], ctime: 1498508667389 }
 }
[23:26:37] Finished 'templates' after 11 ms
```

> Также попробуй добавить в package.json в секцию scripts следующую строку "watch": "gulp watch" и запустить её: npm run watch. Если работает, то проблема с путями у меня в модуле.

Работает, но не компилирует.
Попробую из подсистемы linux. Возможно проблема в винде.

**Comment by mrmlnc** [comment]
В любом случае нужно чиниться для Windows :) 

Займусь в ближайшее время – сейчас нужно по работе пакеты допилить 💃

**Comment by a-gunderin** [comment]
> В любом случае нужно чиниться для Windows :)
> 
> Займусь в ближайшее время – сейчас нужно по работе пакеты допилить 💃

В любом случае, большое спасибо за проделанный труд!!! 💃

**Comment by mrmlnc** [comment]
Посмотрел на проблему глубже: https://github.com/mrmlnc/emitty/blob/master/src/providers/stream.ts#L110 - здесь должен быть `relative` из `utils`, а не `path`. Потестирую ещё завтра и посмотрю как лучше зафиксить. Непонятно почему это не выстреливало, когда я ещё пользовался Windows — возможно, были какие-то обновления Gulp.

**Comment by hettcher** [comment]
Аналогичная проблема.

windows 7 (x64)
gulp 4
gulp CLI 1.4.0
node 8.9.1

**Comment by Ferym26** [comment]
Так как решена трабла и почему ишка закрыта? аналогично таск пишет об успешности, но html не появляются и папка не создается.
win10
CLI version 2.0.0
Local version 4.0.0-alpha.3

**Comment by hettcher** [comment]
@Ferym26 

мне помогло npm i emitty@next
после этого начало всё работать, хотя я устанавливал через npm (последнею версию), но всё же пришлось апдейт сделать, что и решило проблему.

**Comment by Ferym26** [comment]
@hettcher 

а можешь плз тестовый репозиторий с рабочим примером сделать? спасибо!

**Comment by hettcher** [comment]
Если ещё нужно:
https://github.com/hettcher/Gulp-v4
в gulp/templates и gulpfile.babel.js раскомментируй таски (emitty).


ср, 3 янв. 2018 г. в 12:24, Yauhen Hardzei <notifications@github.com>:

**Comment by astelit** [comment]
после npm i emitty@next
выдаёт ошибку на windows 10
TypeError: Cannot read property 'replace' of null
    at Object.normalize (D:\aGulp-4\lab\node_modules\emitty\out\utils\paths.js:7:21)
    at StreamProvider.run (D:\aGulp-4\lab\node_modules\emitty\out\providers\stream.js:31:30)
    at Object.stream (D:\aGulp-4\lab\node_modules\emitty\out\emitty.js:59:53)
    at D:\aGulp-4\lab\app-v17\zGulp\tasks\default\pug.js:40:35
    at taskWrapper (D:\aGulp-4\lab\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (D:\aGulp-4\lab\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by joseffie** [comment]
Всё также таск пишет об успешности, но файлы не компилируются. Как решена проблема?
Win10
CLI version: 2.3.0
Local version: 4.0.2
