### ISSUE TITLE
Не работает с абсолютными путями

### ISSUE THREAD

**Issue by samogot** [mrmlnc/emitty#12]
Для удобства работы, все пути и `glob`ы с которыми приходится работать у меня вынесены в отдельный объект примерно такого вида:
```JavaScript
const emittyModule = require('emitty');

const paths = {
	root: path.join(__dirname, './src/main'),
	app: path.join(__dirname, './src/main/frontend'),
// ...
	pugPages: path.join(__dirname, './src/main/frontend/pages/*.pug'),
	pugs: path.join(__dirname, './src/main/java/**/*.pug'),
// ...
	pugsWatch: [
		path.join(__dirname, './src/main/frontend/pages/*.pug'),
		path.join(__dirname, './src/main/frontend/blocks/**/*.pug'),
		path.join(__dirname, './src/main/java/**/*.pug'),
	],
// ..
};
const emitty = emittyModule.setup(paths.root, 'pug', {basedir: paths.app});
```

Дальше эти пути используются везде, в том числе и в gulp.
Если в галп передавать абсолютны путь, то и в потоке файлы будут передаваться по абсолютному пути. emitty к этому явно не готов, так как индекс у него строится с приведением к относительному пути: https://github.com/mrmlnc/emitty/blob/master/src/services/scanner.ts#L101
а поиск по индексу производится без такого приведения. Не уверен что проблема только в одном месте, так как у себя полечил я ее костылем в виде приведения всех путей к относительному виду:
```
for (let key of Object.keys(paths)) {
	if (paths[key] instanceof Array) {
		for (let key2 of paths[key].keys()) {
			paths[key][key2] = path.relative(process.cwd(), paths[key][key2]);
		}
	}
	else {
		paths[key] = path.relative(process.cwd(), paths[key]);
	}
}
```

**Comment by mrmlnc** [comment]
Спасибо, забыл про этот момент – починю в ближайшее время 💃

**Comment by mrmlnc** [comment]
Closed in favor of issue #26.
