### ISSUE TITLE
Проблема при удалении pug файла при сборке

### ISSUE THREAD

**Issue by HelgaZhizhka** [mrmlnc/emitty#13]
Помогите решить проблему : во время работы watch при удалении pug-файла появляется ошибка :
 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'D:\ProjectsWork\agency\src\modules\page\page.pug'
и приходится перезапускать сборку.
вот сами задачи

	// Modules, pages
	gulp.watch('src/**/*.pug', gulp.series('pages'))
		.on('all', (event, filepath) => {
			global.emittyChangedFile = filepath;
		});

const gulp = require('gulp'),
	emitty = require('emitty').setup('src', 'pug',  {basedir: 'src/modules'}, {
		scanner: { exclude: ['src/static' ] },
		makeVinylFile: true
	}),
	path = require('path'),
	fs = require('fs'),
	config = require('../config'),
	$ = require('gulp-load-plugins')();

gulp.task('pages', () =>
	
	new Promise((resolve, reject) => {
		const sourceOptions = global.watch ? { read: false } : {};
		emitty.scan(global.emittyChangedFile).then(() => {
			config.pug.params.locals = getJsonData('./tmp/data.json');
			gulp.src(config.src.pug, sourceOptions)
				.pipe($.plumber({
					errorHandler: config.errorHandler
				}))
				.pipe($.if(global.isWatch, emitty.filter(global.emittyChangedFile)))
				.pipe($.pug(config.pug.params))
				.pipe($.posthtml(config.posthtmlConfig.plugins, config.posthtmlConfig.options))
				.pipe($.prettify(config.htmlPrettifyConfig))
				.pipe($.debug({title: 'pug to html'}))
				.pipe(gulp.dest(config.dest.root))
				.on('end', resolve)
				.on('error', reject);
		});
	})
)

**Comment by zoxon** [comment]
@HelgaZhizhka как решили эту проблему?

**Comment by mrmlnc** [comment]
@zoxon,

Если проблема проявляется, то было бы классно собрать демо-репозиторий и немного инфы о твоём PC.

**Comment by zoxon** [comment]
@mrmlnc вот репозиторий https://github.com/zoxon/gulp-front/tree/feature/emitty
```
npm 5.3.0
node v8.4.0
yarn 1.1.0
Mac OS High Sierra 10.13 (17A405)
```

**Comment by zoxon** [comment]
Ошибка воспроизводится следующим образом.
Запускаю сборку командой `yarn start` затем дублирую страницу home.pug в test.pug.
После пересборки удаляю файл test.pug
Получаю ошибку 
```js
{ 
  Error: ENOENT: no such file or directory, stat 'source/pages/test.pug'
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'source/pages/test.pug' 
}
```

**Comment by ghost** [comment]
@zoxon у тебя в event передается тип события, если unlink, то файла не существует и по этому появляется ошибка. Я при удалении файлов полностью пересобираю файлы страниц, что бы понять была ли до этого зависимость от удаляемого файла.

**Comment by HelgaZhizhka** [comment]
@zoxon у меня при удалении файла pug было так: ошибка в консоли - Unhandled promise rejection (rejection id: 1), и зависает watch, дальше сборка не идет, приходилось заново запускать . 
Пока на данный момент просто решила так что в задаче html у меня в отдельной function сама сборка

```
function resolvePromise(resolve) {
    return gulp.src(PATH.src.pages, sourceOptions)
      .pipe($.plumber(plumberConfig))
      .pipe($.if(global.watch, emitty.filter(global.emittyChangedFile)))
      .pipe($.pug(pugConfig))
      .pipe($.posthtml(posthtmlConfig.plugins, posthtmlConfig.options))
      .pipe($.prettify(htmlPrettifyConfig))
      .pipe($.debug({title: 'pug to html'}))
      .pipe(gulp.dest(PATH.dest.root))
      .on('end', resolve)
  }
```
и затем в emit она вызывается и на then и на catch

```
return new Promise((resolve, reject) => {
    emitty.scan(global.emittyChangedFile).then(() => {
      resolvePromise(resolve)
    }).catch((err) => {
      console.log(err.message);
      resolvePromise(resolve)
    });
  })
```

Сейчас при удалении pug при watch я получаю сообщение -  Error: ENOENT: no such file or directory, но сборка не зависает, просто еще раз пересобирается
Я сомневаюсь что это верный вариант, но пока он у меня работает оставила так))

**Comment by zoxon** [comment]
@t-shad  я в первую очередь смотрел в эту сторону.
```js
gulp
    .watch("source/**/*.pug", gulp.series(pages, reload))
    .on("all", (event, filepath) => {
      if (event !== "unlink") {
        global.emittyChangedFile = filepath;
      }
    });
```
Вроде работает но блин пересобирать все при удалении страницы, как то это совсем дико.
Пробовал другой пример (stream-advanced) использовать он вообще не работает.
Час экспериментов дал следующее если делать инициализацию внутри промиса то все работает.

```js
export const pages = () => {
  return new Promise((resolve, reject) => {
    const emittyPug = emittySetup("source/pages", "pug");
    emittyPug
      .scan(global.emittyChangedFile)
      .then(() => {
        gulp
          .src(["**/*.pug", "!**/_*.pug"], { cwd: "source/pages" })
          .pipe(plumber(plumberConfig))
          .pipe(
            gulpIf(global.watch, emittyPug.filter(global.emittyChangedFile))
          )
          .pipe(pug(pugConfig))
          .pipe(posthtml(posthtmlConfig.plugins, posthtmlConfig.options))
          .pipe(prettify(htmlPrettifyConfig))
          .pipe(gulp.dest("dest"))
          .on("end", resolve)
          .on("error", reject);
      })
      .catch(err => console.log(err));
  });
};
```

**Comment by zoxon** [comment]
@mrmlnc пожалуйста обновите примеры

**Comment by HelgaZhizhka** [comment]
@zoxon спасибо! обновила у себя по Вашему примеру, теперь не нужно пересобирать при удалении, и все работает)

**Comment by mrmlnc** [comment]
Звучит как баг. То, что ты сделал выше — строит индекс проекта каждый раз при сборке, то есть каждый раз сканирует проект. Очевидно, что это плохо. Займусь этой проблемой в понедельник.

Кажется, что перед тем, как получать состояние файла нужно проверить его существование и, если его нет, то собирать все файлы, которые к нему относились.

 Да, emitty сейчас не идеален и в нём есть баги, которые вовремя чинить времени не хватает.

**Comment by ainursharaev** [comment]
` watch('./pug/**/*.pug', series(pug)).on(['change','add'], (_, filepath) => global.emittyChangedFile = filepath);
`
Решил пока что таким образом

**Comment by zoxon** [comment]
Рабочий пример
https://github.com/zoxon/gulp-front/blob/master/gulp/tasks/templates.js

**Comment by mrmlnc** [comment]
Closed in favor of issue #26.
