### ISSUE TITLE
Поправить документацию.

### ISSUE THREAD

**Issue by ghost** [mrmlnc/emitty#17]
Привет, правильно ли я понимаю, что в документации не правильно написан пример использования getDependencies:
`emitty.scan().then(() => {
  console.log(emitty.getDependencies('a.pug'));
  // ['components/b.pug']
});`

А должно быть так:

`emitty.scan().then(() => {
  console.log(emitty.resolver.getDependencies('a.pug'));
  // ['components/b.pug']
});`

**Comment by rndD** [comment]
Да ты прав. Фиксим тут #18

**Comment by mrmlnc** [comment]
Спасибо за репорт и исправление 🌮
