### ISSUE TITLE
Зависает задача.

### ISSUE THREAD

**Issue by AntonEssenetial** [mrmlnc/emitty#19]
Добрый день.
Подскажите как заставить emitty работать с browserSync правильно? 
При сохранении файла запускается задача pug, вотчер видит активность, запускает pug и reload и на этом все, если я повторно сохраняю больше ничего не происходит, в консоле тишина. Будто бы все зависло.
Скрин:
![2017-10-30 21 59 16](https://user-images.githubusercontent.com/3510870/32190081-4d34c4b2-bdb5-11e7-8faf-5083d46c590c.png)
Если убираю reload с таска watch и добавляю его в таск pug, происходит следующие:
![2017-10-30 22 02 04](https://user-images.githubusercontent.com/3510870/32190214-be15ad72-bdb5-11e7-828e-4ff579840ea1.png)
Как видите происходит одна компиляция всех файлов с зависимостями и 3 раза подряд обновление браузера, так как редактирую например header.pug а он зависим с тремя страницами, если компилирую файл без зависимости тогда все кул.

    gulp.task('pug', (cb) => {

      var jsonData = getJsonData('./tmp/data.json');
      options.pug.locals = jsonData;

      new Promise((resolve, reject) => {
        const sourceOptions = global.watch ? { read: false } : {};

        emitty.scan(global.changedStyleFile).then(() => {
            gulp.src('source/pages/*.pug', sourceOptions)
                .pipe(gulpif(global.watch, emitty.filter(global.emittyChangedFile)))
                .pipe($.pug(options.pug))
                .pipe(gulp.dest('./dist/'))
                .on('end', resolve)
                .on('error', reject)
                // .pipe(browserSync.stream());
          });
      })
      cb();
    });

    gulp.task('watch', () => {
      global.watch = true;
      gulp.watch('source/**/*.pug', gulp.series('pug', browserSync.reload))
        .on('all', (event, filepath) => {
            global.emittyChangedFile = filepath;
        });
    });

**Comment by mrmlnc** [comment]
Ничего конкретного сказать не могу, так как `browser-sync` выбросил на помойку, как только нашёл `gulp-connect`. Кажется, что нужно поменять местами:

```diff
  new Promise((resolve, reject) => {
    const sourceOptions = global.watch ? { read: false } : {};

    emitty.scan(global.changedStyleFile).then(() => {
        gulp.src('source/pages/*.pug', sourceOptions)
            .pipe(gulpif(global.watch, emitty.filter(global.emittyChangedFile)))
            .pipe($.pug(options.pug))
            .pipe(gulp.dest('./dist/'))
+          .pipe(browserSync.stream());
            .on('end', resolve)
            .on('error', reject)
-          .pipe(browserSync.stream());
      });
  })
```

**Comment by AntonEssenetial** [comment]
У меня обратная ситуация всю дорогу пользовался gulp-connect а теперь browserSync. Я пробовал менять местами результат тот же, браузер перезагружается несколько раз подряд, Поставил gulp-connect все нормально, только он меня не очень устраивает, в нем вроде нет css hot-replacement при сборки css перезагружается браузер, я старался наоборот сэкономить время а тут получается лишняя перезагрузка браузра, да и браузер он автоматом не открывает. Ладно буду думать что делать.

**Comment by mrmlnc** [comment]
Могу лишь посоветовать сделать, как вот тут:

https://github.com/mrmlnc/yellfy

Несколько раз он перезагружается потому, что в стрим у тебя уходит три файла.

**Comment by AntonEssenetial** [comment]
Спасибо solved! Вы подтолкнули на мысль. Да уходило в поток, поставил в поток {once: true}; и  теперь все круто.
