### ISSUE TITLE
Совместимость с Node v.8.9.0?

### ISSUE THREAD

**Issue by TheUnchainedPug** [mrmlnc/emitty#20]
Поставил последнюю версию ноды 8.9.0, собственно, когда запускаю задачу, gulp доходит до момента компиляции pug файлов - выпадает ошибка.
![default](https://user-images.githubusercontent.com/16023592/32499394-466f3de8-c3f4-11e7-9259-09ee20e72c0c.PNG)

Сам конфиг можно глянуть тут: https://github.com/TheUnchainedPug/pug-sass-gulp/blob/master/tasks/views.js

Буду благодарен за помощь.

**Comment by hettcher** [comment]
У меня не выбивает ошибки с 8.9.0, но у меня другая проблема, gulp.watch не работает (испробовал все примеры https://github.com/mrmlnc/emitty#how-to-use-with-gulp )
task.templates работает, если запускать его отдельно, а если запустить gulp.watch, при пересохранение любых файлов (как include, так и index.pug) ничего не меняется, как будто их не видит.
http://take.ms/0F8mm

**Comment by mrmlnc** [comment]
Привет, попробуй сделать так:

```js
emitty.scan(global.emittyChangedFile)
    .then(() => {
        // Какой-то код тут
    })
    .catch(console.error);
```

**Comment by hettcher** [comment]
Привет)
Я уже узнал где была проблема, нужно было ещё обновить emitty npm i
emitty@next, после этого всё заработало. Хотя я и так устанавливал
последнею версию, но помогло решить проблему лишь то, что я написал.

2017-12-18 21:29 GMT+02:00 Denis Malinochkin <notifications@github.com>:

**Comment by mrmlnc** [comment]
Closed in favor of issue #26.
