### ISSUE TITLE
Помогите разобраться

### ISSUE THREAD

**Issue by Fenricage** [mrmlnc/emitty#23]
В общем, очень сильно понравилась идея Emitty, но я не совсем понимаю каким образом, и опираясь на какие ключевые слова она создаёт зависимости.

Пробема следующая - после установки и настройки, в скорости компиляции сборка не прибавила. Думал что проблема в настройках Emitty, но манипуляции не помогли и решил создать ишью

вот что выдаёт emitty.storage() - **в самом низу лог**
смущает что у некоторых компонентов, страниц нет зависимостей совсем, и именно при их обновлении парсятся все страницы

А вот с  'blocks/news.pug' всё работает хорошо, обновляется только она, вот только пользы от этого мало, ведь она служит для меня точкой входа, а основная часть страницы подключается сюда через миксин  **+news()**, и вот при внесении изменений в этот миксин обновляется всё абсолютно. Можете помочь? Очень хочется чтобы работало быстро, проект растёт)) Заранее спасибо

Вот ссылка на весь тестовый проект:
https://github.com/Fenricage/Emitty-test/blob/master/gulpfile.js

`{ 'blocks/checkout.pug': 
   { dependencies: [ 'blocks/template.pug' ],
     ctime: 1524136102899 },
  'blocks/home.pug': 
   { dependencies: [ 'blocks/template.pug' ],
     ctime: 1524141224356 },
  'blocks/index.pug': 
   { dependencies: [ 'blocks/template.pug' ],
     ctime: 1524124749427 },
  'blocks/map.pug': { dependencies: [], ctime: 1524136555842 },
  'blocks/order.pug': { dependencies: [], ctime: 1524136549166 },
  'blocks/item.pug': 
   { dependencies: [ 'blocks/template.pug' ],
     ctime: 1524128731038 },
  'blocks/news.pug': 
   { dependencies: [ 'blocks/template.pug' ],
     ctime: 1524136056890 },
  'blocks/template.pug': 
   { dependencies: 
      [ 'blocks/_assets/bemto/bemto.pug',
        'blocks/head/head.pug',
        'blocks/header/header.pug',
        'blocks/head-line/head-line.pug',
        'blocks/intro/intro.pug',
        'blocks/title/title.pug',
        'blocks/pages/item/item.pug',
        'blocks/pages/news/news.pug',
        'blocks/pages/checkout/checkout.pug',
        'blocks/pages/home/home.pug',
        'blocks/pages/order/order.pug',
        'blocks/pages/map/map.pug' ],
     ctime: 1524136747762 },
  'blocks/head/head.pug': { dependencies: [], ctime: 1524128727734 },
  'blocks/header/header.pug': { dependencies: [], ctime: 1524136911726 },
  'blocks/head-line/head-line.pug': { dependencies: [], ctime: 1524128755161 },
  'blocks/intro/intro.pug': { dependencies: [], ctime: 1524129106127 },
  'blocks/title/title.pug': { dependencies: [], ctime: 1524128765479 },
  'blocks/_assets/bemto/bemto.pug': 
   { dependencies: [ 'blocks/_assets/bemto/lib/index.pug' ],
     ctime: 1523715626976 },
  'blocks/pages/checkout/checkout.pug': { dependencies: [], ctime: 1524136404066 },
  'blocks/pages/item/item.pug': { dependencies: [], ctime: 1524136400995 },
  'blocks/pages/home/home.pug': { dependencies: [], ctime: 1524136812060 },
  'blocks/pages/map/map.pug': { dependencies: [], ctime: 1524141232971 },
  'blocks/pages/news/news.pug': { dependencies: [], ctime: 1524136821564 },
  'blocks/pages/order/order.pug': { dependencies: [], ctime: 1524136836037 },
  'blocks/_assets/bemto/lib/bemto.pug': { dependencies: [], ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/bemto_custom_tag.pug': { dependencies: [], ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/bemto_tag.pug': 
   { dependencies: [ 'blocks/_assets/bemto/lib/bemto_custom_tag.pug' ],
     ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/helpers.pug': { dependencies: [], ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/index.pug': 
   { dependencies: 
      [ 'blocks/_assets/bemto/lib/helpers.pug',
        'blocks/_assets/bemto/lib/settings.pug',
        'blocks/_assets/bemto/lib/bemto_tag.pug',
        'blocks/_assets/bemto/lib/bemto.pug' ],
     ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/settings.pug': 
   { dependencies: [ 'blocks/_assets/bemto/lib/tag_metadata.pug' ],
     ctime: 1523715626975 },
  'blocks/_assets/bemto/lib/tag_metadata.pug': { dependencies: [], ctime: 1523715626975 } }
`

**Comment by Fenricage** [comment]
Если есть возможность - дайте ссылку на проект который успешно использует emitty

**Comment by mrmlnc** [comment]
Closed in favor of issue #26.
