### ISSUE TITLE
Не сканируются изменения при подключении google fonts

### ISSUE THREAD

**Issue by chehonte** [mrmlnc/emitty#6]
Здравсвуйте!

Появился странный баг, еле отловил. Есть layout в котором подключается header, footer. Далее этот layout уже соответственно используется через extends. 

Когда я подключаю google fonts например
```jade
link(href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css')
```
то изменения в header и footer во время watch не применяются и конечные html файлы компилятся без них, стоит закомментировать строку с подключением шрифта, все сразу работает нормально.

Код layout
```jade
doctype html
html
    head
        meta(charset='utf-8')
        meta(http-equiv='X-UA-Compatible', content='IE=edge')
        meta(name='viewport', content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
        link(href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css')
        link(href="./css/prev.css", rel="stylesheet")
        link(href="./css/main.css", rel="stylesheet")
        block title
            title Test title
        body
            include ../blocks/header
            block content
            include ../blocks/footer
            block scripts
```

Код index.pug
```jade
extends pug/layout/base

block title
    title Pages List

block content
    | content
```

Код таска
```javascript
return new Promise(function(resolve, reject){
    plugins.emitty.scan(global.emittyChangedFile).then(function(){
        gulp.src(path.src.pug)
            .pipe(plugins.plumber({errorHandler: plugins.notify.onError({
                message: "<%= error.message %>",
                title  : "PUG Error!"
            })}))
            .pipe(plugins.if(global.watch, plugins.emitty.filter(global.emittyChangedFile)))
            .pipe(plugins.pug({ pretty: true }))
            .pipe(gulp.dest(path.build.pug))
            .on('end', resolve)
            .on('error', reject);
        });
});
```

P.S. Если вносить изменения в index.pug, то все работает нормально. Не применяются изменения в include файлах.

**Comment by chehonte** [comment]
Если перенести include в index.pug то все работает нормально, а вот в layout почему то не детектятся изменения.

**Comment by mrmlnc** [comment]
Привет,

Скорее всего что-то вызывает ошибку при парсинге зависимостей и файлы магическим образом пропадают хранилища.

Если будет время, посмотрю сегодня днем.

**Comment by chehonte** [comment]
Еще момент, в любом случае в global.emittyChangedFile измененный файл попадает, разницы нет с шрифтом или без.

```javascript
gulp.watch(path.watch.pug, gulp.series('pug:dev', 'reload'))
.on('all', function(event, filepath){
    global.emittyChangedFile = filepath;
});
```

**Comment by mrmlnc** [comment]
>  в global.emittyChangedFile измененный файл попадает, разницы нет с шрифтом или без.

Ну это обычный вотчер за файлами, который в любом случае выкинет изменившийся файл.

Проблема оказалась в том, что emitty принимает `https://...` за комментарий (комментарий начинается с `//`). Скоро выпущу патч-релиз.

**Comment by chehonte** [comment]
@mrmlnc Отлично! Спасибо!

**Comment by mrmlnc** [comment]
Должно быть исправлено в версии `1.3.1`. Если проблема не исправлена, то пиши, вопрос переоткрою.

**Comment by chehonte** [comment]
@mrmlnc Все работает! Спасибо за скорость!)
