### ISSUE TITLE
dont work with pug basedir option

### ISSUE THREAD

**Issue by avdeev** [mrmlnc/emitty#7]
I use basedir option for gulp-pug and include partials with absolute path.
Emitty doesnt find dependencies for this files.

*Example:*

```js
.pipe(pug({
  basedir: paths.HTML_SOURCE_BASE,
}))
 ```

```pug
include /partials/footer_app_link
```

Emitty works well for includes with relative paths

**Comment by mrmlnc** [comment]
Well, I think we can start work on this issue in the current sprint. Maybe you can provide minimal repository with this problem?

**Comment by mrmlnc** [comment]
Please, look at `emitty@1.4.0` – https://github.com/mrmlnc/emitty/releases/tag/1.4.0.
