### ISSUE TITLE
Не компилирует файл

### ISSUE THREAD

**Issue by librisius** [mrmlnc/emitty#9]
Пытаюсь внедрить emitty в свой проект, с конфигом ниньзя. Отрабатывает watcher и удачно ничего не компирирует. Иногда выдаёт предупрежения node. В чем может быть проблема?

![screenshot_10](https://cloud.githubusercontent.com/assets/7526050/26779867/d088238e-49ef-11e7-8eff-2f5008ae166e.png)
![screenshot_11](https://cloud.githubusercontent.com/assets/7526050/26779868/d0e9878c-49ef-11e7-9b9d-bf5feb68da5b.png)

версия ноды 7.10.00

**Comment by librisius** [comment]
Изменила пути, на те что были изначально, добавила папки как в примерах. Ошибки нет но и файлы не создает.

**Comment by librisius** [comment]
Есть подозрения что нет поддержки layout

**Comment by mrmlnc** [comment]
Привет,

Для того, чтобы посмотреть и решить твою проблему мне нужно немного данных — файловую структуру твоего проекта. 

Когда я писал этот модуль Jade/Pug поддерживал подключение файлов только в `include` и `extends` — не думаю, что сейчас что-то поменялось.

Судя по ошибке вместо пути до изменившегося файла передается что-то другое. Я смогу вечером посмотреть правильность примеров для текущей версии Gulp.

**Comment by mrmlnc** [comment]
А ещё у тебя очень странный код gulp-таски, потому что ты пытаешься использовать сразу несколько вариантов применения Emitty.

**Comment by librisius** [comment]
![screenshot_17](https://cloud.githubusercontent.com/assets/7526050/26819784/182a69a4-4aa9-11e7-855c-c0e237f12857.png)
Вот файловая система проекта. Красным выделено всё необходимое для понимания. На днях перепробывала и другие плагины и наверно Я поняла в чем проблема. если файлы находится в папках include и extends (а у меня именно такие названия), то при компиляции они игнорируются. С этим плагином тоже самое. Так как миксины работали нормально. Почему так, Я до конца не понимаю, но из твоей статьи нашла причину

```
function getPaths(source) {
  const match = source.match(/^\s*(include|extends)\s(.*)/gm);

  if (match) {
    return match.map((match) => match.replace(/\s*(include|extends)./g, '') + '.pug');
  }

  return null;
}
```

тут упонимание как раз двух этих папок. Не подскажешь что может быть не так?

Скрин с конфигом выше это один из... После написания тикета, Я пробовала все из списка и не миксуя их. Естественно отличие от скаченных мною файлов только строка с дефолтным таском. Всё работает д тех пор пока не назовёшь папки как Я писала выше.

**Comment by mrmlnc** [comment]
Смотрю на код выше и не понимаю где это у меня используется. Поискал – нигде.

Давай решим проблему фундаментально: сделай демо-репозиторий, где воспроизводится проблема и настроен Emitty – и мы решим твою проблему.

**Comment by mrmlnc** [comment]
Закрываю, потому что устарело. Переоткрою, как только будут свежие новости.
